In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
sqrt = np.sqrt(arr)
print("Square root of array is: ", sqrt)

cos = np.cos(arr)
print("Cosine of array is: ", cos)

sin = np.sin(arr)
print("Sine of array is: ", sin)

exp = np.exp(arr)
print("Exponential of array is: ", exp)


floor = np.floor(arr)
print("Floor of array is: ", floor)

Square root of array is:  [1.         1.41421356 1.73205081 2.         2.23606798]
Cosine of array is:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Sine of array is:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Exponential of array is:  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Floor of array is:  [1. 2. 3. 4. 5.]


In [4]:
# Shape manipulation
new_cyclist_trials = np.array([[1, 2, 3], [4, 5, 6]])

new_cyclist_trials.ravel()

new_cyclist_trials = new_cyclist_trials.reshape(3, 2)

print(new_cyclist_trials)


[[1 2]
 [3 4]
 [5 6]]


In [5]:
one_d_array = np.arange(12)

print(one_d_array)

one_d_array = one_d_array.reshape(3, 4)

print(one_d_array)

zeros_array = np.zeros((3, 4))

print(zeros_array)

ones_array = np.ones((3, 4))

print(ones_array)

linspace_array = np.linspace(0, 2, 9)

print(linspace_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [6]:
ndarray = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape: ", ndarray.shape)
print("Dimension: ", ndarray.ndim)
print("Size: ", ndarray.size)
print("Type: ", ndarray.dtype)
print("Item size: ", ndarray.itemsize)

Shape:  (2, 3)
Dimension:  2
Size:  6
Type:  int64
Item size:  8


In [7]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

add = A + B
print("Addition: ", add)
sub = A - B
print("Subtraction: ", sub)

print(np.add(A, B))
print(np.subtract(A, B))
print(np.multiply(A, B))
print(np.power(A, 2))
print(np.abs(A))


Addition:  [[3 1]
 [3 5]]
Subtraction:  [[-1  1]
 [-3 -3]]
[[3 1]
 [3 5]]
[[-1  1]
 [-3 -3]]
[[2 0]
 [0 4]]
[[1 1]
 [0 1]]
[[1 1]
 [0 1]]


In [8]:
x = np.arange(0, 10, 0.5)

print(np.where(x > 5, 10, 0))

condition_list = [x < 3, x > 8]
choice_list = [x**2, x**3]

np.select(condition_list, choice_list)

[ 0  0  0  0  0  0  0  0  0  0  0 10 10 10 10 10 10 10 10 10]


array([0.00000e+00, 2.50000e-01, 1.00000e+00, 2.25000e+00, 4.00000e+00,
       6.25000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 6.14125e+02, 7.29000e+02, 8.57375e+02])

In [9]:
temp = np.array([x for x in range(1, 13)])
print(temp)
temp = temp.reshape(2, 2, 3)
print(temp)

mini = np.min(temp)
print("Minimum: ", mini)

min_row = np.min(temp, axis=1)
print("Minimum row: ", min_row)

median = np.median(temp, axis=1)
print("Median: ", median)

standard_dev = np.std(temp, axis=1)
print("Standard Deviation: ", standard_dev)



[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Minimum:  1
Minimum row:  [[1 2 3]
 [7 8 9]]
Median:  [[ 2.5  3.5  4.5]
 [ 8.5  9.5 10.5]]
Standard Deviation:  [[1.5 1.5 1.5]
 [1.5 1.5 1.5]]


In [10]:
# Indexing and Slicing

array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

print(array_1d[0]) # 1
print(array_1d[1:5]) # [2, 3, 4, 5]
print(array_1d[1:5:2]) # [2, 4]
print(array_1d[::2]) # [1, 3, 5, 7, 9]
print(array_1d[::-1]) # [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
print(array_1d[-1]) # 10
print(array_1d[-3:-1]) # [8, 9]
print(array_1d[-3:-1:2]) # [8]


print(array_2d[0, 0]) # 1
print(array_2d[0, 1:3]) # [2, 3]
print(array_2d[0, 1:3:2]) # [2]
print(array_2d[0, ::2]) # [1, 3]


print(array_3d[0, 0:, 0:]) # [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

1
[2 3 4 5]
[2 4]
[1 3 5 7 9]
[10  9  8  7  6  5  4  3  2  1]
10
[8 9]
[8]
1
[2 3]
[2]
[1 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
